/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Car;
import model.ServiceRecords;
import java.text.*;
import model.ServiceRecordsHistory;



/**
 *
 * @author sumeetsunildeshpande
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Car car;
    int flag=0;
    ServiceRecordsHistory history;
    public CreateJPanel(Car car, ServiceRecordsHistory history) {
        initComponents();
        this.car=car;
        this.history=history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        lblCarName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblEngineNo = new javax.swing.JLabel();
        txtEngineNo = new javax.swing.JTextField();
        lblSeatNumber = new javax.swing.JLabel();
        txtSeatNumbers = new javax.swing.JTextField();
        lblLicensePlates = new javax.swing.JLabel();
        txtLicensePlates = new javax.swing.JTextField();
        lblOwnerName = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        lblTelephoneNumber = new javax.swing.JLabel();
        txtOwnerNumber = new javax.swing.JTextField();
        lblOwnerEmailAddresses = new javax.swing.JLabel();
        txtOwnerEmailAddresses = new javax.swing.JTextField();
        lblOwnerDriverLicense = new javax.swing.JLabel();
        txtOwnerDriverLicense = new javax.swing.JTextField();
        lblOwnerSSN = new javax.swing.JLabel();
        txtOwnerSSN = new javax.swing.JTextField();
        lblOwnerAddress = new javax.swing.JLabel();
        txtOwnerAddress = new javax.swing.JTextField();
        lblServiceRecords = new javax.swing.JLabel();
        lblWarrantyYear = new javax.swing.JLabel();
        txtWarrantyYear = new javax.swing.JTextField();
        lblPhotos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtServiceDate = new javax.swing.JTextField();
        lblMileage = new javax.swing.JLabel();
        txtMileage = new javax.swing.JTextField();
        lblGas_Capacity = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        btnAddRecord = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();

        lblBrand.setText("Brand");

        lblModel.setText("Model");

        lblColor.setText("Color");

        lblYear.setText("Year");

        lblCarName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblCarName.setText("Create Car");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblEngineNo.setText("Engine number");

        lblSeatNumber.setText("Seat Numbers");

        lblLicensePlates.setText("License Plate");

        lblOwnerName.setText("Owner Name");

        lblTelephoneNumber.setText("Owner Telephone Number");

        lblOwnerEmailAddresses.setText("Owner Email addresses");

        lblOwnerDriverLicense.setText("Owner Driver License");

        lblOwnerSSN.setText("Owner Social Security Number");

        lblOwnerAddress.setText("Owner Address ");

        lblServiceRecords.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblServiceRecords.setText("Service Records");

        lblWarrantyYear.setText("Warranty Year");

        lblPhotos.setText("Photos");

        jLabel1.setText("Date");

        lblMileage.setText("City");

        lblGas_Capacity.setText("Branch Name");

        btnAddRecord.setText("Add");
        btnAddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecordActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServiceRecords)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMileage)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblColor)
                                        .addComponent(lblModel)
                                        .addComponent(lblYear)
                                        .addComponent(lblBrand))
                                    .addComponent(lblEngineNo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLicensePlates)
                                        .addComponent(lblSeatNumber))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblWarrantyYear)
                                        .addGap(6, 6, 6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(lblGas_Capacity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtServiceDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                                .addComponent(txtMileage, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(btnAddRecord)))
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(txtEngineNo)
                                    .addComponent(txtSeatNumbers)
                                    .addComponent(txtLicensePlates)
                                    .addComponent(txtWarrantyYear)
                                    .addComponent(txtBrand)
                                    .addComponent(txtModel)
                                    .addComponent(txtColor))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblOwnerAddress)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblPhotos)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblOwnerName)
                                                            .addComponent(lblTelephoneNumber)
                                                            .addComponent(lblOwnerEmailAddresses)
                                                            .addComponent(lblOwnerDriverLicense))
                                                        .addGap(44, 44, 44)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtOwnerDriverLicense)
                                                            .addComponent(txtOwnerEmailAddresses)
                                                            .addComponent(txtOwnerNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                                            .addComponent(txtOwnerName)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblOwnerSSN)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(211, 211, 211))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(353, 353, 353)
                                .addComponent(btnUpload))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(lblCarName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtOwnerAddress, txtOwnerDriverLicense, txtOwnerEmailAddresses, txtOwnerName, txtOwnerNumber, txtOwnerSSN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCarName)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerName)
                    .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelephoneNumber)
                    .addComponent(txtOwnerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerEmailAddresses)
                    .addComponent(lblColor)
                    .addComponent(txtOwnerEmailAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerDriverLicense)
                    .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEngineNo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOwnerSSN)
                        .addComponent(txtOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeatNumber)
                    .addComponent(txtSeatNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerAddress)
                    .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicensePlates)
                    .addComponent(txtLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhotos)
                    .addComponent(btnUpload))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWarrantyYear)
                            .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(lblServiceRecords)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtServiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMileage)
                            .addComponent(txtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGas_Capacity)
                            .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddRecord))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(btnSave)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBrand, txtColor, txtModel, txtYear});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtOwnerAddress, txtOwnerDriverLicense, txtOwnerEmailAddresses, txtOwnerName, txtOwnerNumber, txtOwnerSSN});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCapacity, txtMileage, txtServiceDate});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String valueCheck;
        int numberCheck;
        
        //Brand
        valueCheck=txtBrand.getText().trim();
        if(valueCheck.isEmpty() || valueCheck.length()<=2 || ! valueCheck.chars().allMatch( Character::isLetter ))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid Brand Name atleast 2 charcters");
             return;
        }
        else
        {
            car.setBrand(valueCheck);
        }
        
        
        //Model
        valueCheck=txtModel.getText().trim();
        if(valueCheck.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please Enter Model Name");
             return;
        }
        else
        {
           car.setModel(txtModel.getText());
        }
        
        //Color
        valueCheck=txtColor.getText().trim();
        if(valueCheck.isEmpty() || valueCheck.length()<3 || ! valueCheck.chars().allMatch( Character::isLetter ))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid Color Name");
             return;
        }
        else
        {
            car.setColor(valueCheck);
        }
        
        //Year
      valueCheck=txtYear.getText().trim();
      if(valueCheck.isEmpty() || valueCheck.length()!=4 || valueCheck.charAt(0)=='0' || ! valueCheck.chars().allMatch( Character::isDigit ))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid Year of 4 digits and should not start with 0 ");
             return;
        }
        else
        {
            car.setYear(Integer.parseInt(valueCheck));
        }
      
      //Engine Number
      valueCheck=txtEngineNo.getText().trim();
       if(valueCheck.isEmpty() || !(valueCheck.length()>10 && valueCheck.length()<18)  ||! (valueCheck.chars().allMatch( Character::isLetterOrDigit ) ))
        {        
                JOptionPane.showMessageDialog(this,"Please Enter Valid  Engine Number of 11 to 17 character");
                System.out.println(valueCheck.chars().allMatch( Character::isDigit ));
                
                return;
        }
       else
        {
            car.setEngine_no(valueCheck);
        }
      
      //Seat Number
       valueCheck=txtSeatNumbers.getText().trim();
       if(valueCheck.isEmpty() ||! (valueCheck.chars().allMatch( Character::isDigit ) ))
        {        
                JOptionPane.showMessageDialog(this,"Please Enter Valid Seat Number");
                return;
        }
       else
        {
            car.setSeatnumbers(Integer.parseInt(valueCheck));
        }
      
      
      //License Plate
       valueCheck=txtLicensePlates.getText().trim();
       if(valueCheck.isEmpty() || (valueCheck.length()!=6 )  ||! (valueCheck.chars().allMatch( Character::isLetterOrDigit ) ))
        {        
                JOptionPane.showMessageDialog(this,"Please Enter Valid  License Plate of 6 digits");
                return;
        }
       else
        {
            car.setLicenseplates(valueCheck);
        }
       
       //Warranty Year
        valueCheck= txtWarrantyYear.getText().trim();
      if(valueCheck.isEmpty() || ! valueCheck.chars().allMatch( Character::isDigit ))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid Warranty Year in digits ");
             return;
        }
        else
        {
            car.setWarranty_year(Integer.parseInt(valueCheck));
        }
      
      //Owner Name
       valueCheck=txtOwnerName.getText().trim();
      if(valueCheck.isEmpty() || valueCheck.length()<2 || ! valueCheck.chars().allMatch( Character::isLetter ))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Owner Name");
             return;
        }
        else
        {
            car.setOwner_name(valueCheck);
        }
      
     //Owner Telephone Number
       valueCheck= txtOwnerNumber.getText().trim();
      if(valueCheck.isEmpty() || valueCheck.length()!=10 ||! valueCheck.chars().allMatch( Character::isDigit ))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid Phone Number of 10 digit");
             return;
        }
        else
        {
            car.setOwner_telephone_numbers(valueCheck);
        }
      
      
   //Owner Email Address 
        valueCheck= txtOwnerEmailAddresses.getText().trim();
        if(validateEmailAddress(valueCheck)){
            car.setOwner_email_addresses(valueCheck);
        }
        else{
            JOptionPane.showMessageDialog(this,"Please Enter Valid Email Address");
             return;
        }
         
     
       // Owner Driver License
       valueCheck= txtOwnerDriverLicense.getText().trim();
       if(valueCheck.isEmpty() || (valueCheck.length()!=11 )  ||! (valueCheck.chars().allMatch( Character::isLetterOrDigit ) ))
        {        
                JOptionPane.showMessageDialog(this,"Please Enter Valid  License Number of 11 Digits");
                return;
        }
       else
        {
           car.setOwner_driverlicense(valueCheck);
        }
        // Owner SSN
        valueCheck=txtOwnerSSN.getText().trim();
        if(valueCheck.isEmpty() || (valueCheck.length()!=9 )|| (valueCheck.charAt(0)=='0')  ||! (valueCheck.chars().allMatch( Character::isDigit ) ))
        {        
                JOptionPane.showMessageDialog(this,"Please Enter Valid  SSN Number of 9 Digits and should not start with 0");
                return;
        }
       else
        {
           car.setOwner_SSN(Integer.parseInt(valueCheck));
        }
        // Owner Address 
        valueCheck=txtOwnerAddress.getText();
           if(valueCheck.isEmpty() )
        {        
                JOptionPane.showMessageDialog(this,"Please Enter Valid  Owner  address");
                return;
        }
       else
        {
           car.setOwner_address(valueCheck);
        }
        
        if(car.getPhoto()==null)
        {
             JOptionPane.showMessageDialog(this,"Please add Photo");
             return;
        }
        
        if(flag==0)
        {
            JOptionPane.showMessageDialog(this,"Please add ServiceRecords");
             return;
        }
        JOptionPane.showMessageDialog(this,"Car Details Saved ");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecordActionPerformed
        // TODO add your handling code here:
        ServiceRecords record=history.addNewRecords();
        if(!isValidDate(txtServiceDate.getText()))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid Date in dd/MM/yyyy");
             return;
        }
         if(txtMileage.getText().trim().isEmpty() || !(txtMileage.getText().trim().chars().allMatch( Character::isLetter ) ) )
        {
            JOptionPane.showMessageDialog(this,"Please Enter Valid City ");
            return;
        }
        if(txtCapacity.getText().trim().isEmpty() || !(txtMileage.getText().trim().chars().allMatch( Character::isLetter )))
        {
             JOptionPane.showMessageDialog(this,"Please Enter Valid Branch name");
             return;
        }
         record.setDate(txtServiceDate.getText());
             txtServiceDate.setText("");
              record.setMileage(txtMileage.getText().trim());
              txtMileage.setText("");
                record.setGas_capacity(txtCapacity.getText());
             txtCapacity.setText("");
             
      JOptionPane.showMessageDialog(this,"Service Record Added");
      flag=1;
        
           
        
        
    }//GEN-LAST:event_btnAddRecordActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
  
    JFileChooser upload = new JFileChooser();
        FileNameExtensionFilter file=new FileNameExtensionFilter("*.images", "jpg", "jpeg", "png");
        upload.addChoosableFileFilter(file);
        int selected= upload.showOpenDialog(null);
        if(selected==JFileChooser.APPROVE_OPTION){
            File uploadedImage=upload.getSelectedFile();
            String path= uploadedImage.getAbsolutePath();
            JOptionPane.showMessageDialog(null, "Photo uploaded Successfully.");
            
            ImageIcon i=new ImageIcon(path); 
            
            Image i1=i.getImage().getScaledInstance(lblPhoto.getWidth(),lblPhoto.getHeight(), Image.SCALE_SMOOTH);
          
            car.setPhoto(path);
            lblPhoto.setIcon(new ImageIcon(car.getPhoto()));
        }
       
    }//GEN-LAST:event_btnUploadActionPerformed
    public   boolean validateEmailAddress(String emailString)
    {
       
          String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(emailString);
           return m.matches();
    }
  public  boolean isValidDate(String date) {

        boolean valid = false;
         SimpleDateFormat simpledateformat = new SimpleDateFormat("dd/MM/yyyy");
          simpledateformat.setLenient(false);

        try {
            simpledateformat.parse(date);
           
            valid = true;

        } catch (ParseException e) {
            e.printStackTrace();
            valid = false;
        }

        return valid;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRecord;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblGas_Capacity;
    private javax.swing.JLabel lblLicensePlates;
    private javax.swing.JLabel lblMileage;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerAddress;
    private javax.swing.JLabel lblOwnerDriverLicense;
    private javax.swing.JLabel lblOwnerEmailAddresses;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerSSN;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotos;
    private javax.swing.JLabel lblSeatNumber;
    private javax.swing.JLabel lblServiceRecords;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblWarrantyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicensePlates;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerAddress;
    private javax.swing.JTextField txtOwnerDriverLicense;
    private javax.swing.JTextField txtOwnerEmailAddresses;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtOwnerNumber;
    private javax.swing.JTextField txtOwnerSSN;
    private javax.swing.JTextField txtSeatNumbers;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtWarrantyYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
