/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.ServiceRecords;
import model.ServiceRecordsHistory;

/**
 *
 * @author sumeetsunildeshpande
 */
public class viewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewJPanel
     */
 Car car;
 ServiceRecordsHistory history;
    public viewJPanel(Car car,ServiceRecordsHistory history) {
        initComponents();
        this.car=car;
        this.history=history;
        displayCar();
        populateRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCar = new javax.swing.JLabel();
        lblTelephoneNumber = new javax.swing.JLabel();
        txtOwnerNumber = new javax.swing.JTextField();
        lblOwnerEmailAddresses = new javax.swing.JLabel();
        txtOwnerEmailAddresses = new javax.swing.JTextField();
        lblOwnerDriverLicense = new javax.swing.JLabel();
        txtOwnerDriverLicense = new javax.swing.JTextField();
        lblOwnerSSN = new javax.swing.JLabel();
        txtOwnerSSN = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblOwnerAddress = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtOwnerAddress = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        lblEngineNo = new javax.swing.JLabel();
        lblServiceRecords = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtEngineNo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        lblSeatNumber = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtSeatNumbers = new javax.swing.JTextField();
        lblLicensePlates = new javax.swing.JLabel();
        lblWarrantyYear = new javax.swing.JLabel();
        txtLicensePlates = new javax.swing.JTextField();
        txtWarrantyYear = new javax.swing.JTextField();
        lblOwnerName = new javax.swing.JLabel();
        lblPhotos = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        lblPhoto = new javax.swing.JLabel();

        lblCar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblCar.setText("View Car");

        lblTelephoneNumber.setText("Owner Telephone Number");

        lblOwnerEmailAddresses.setText("Owner Email addresses");

        lblOwnerDriverLicense.setText("Owner Driver License");

        lblOwnerSSN.setText("Owner SSN");

        lblBrand.setText("Brand");

        lblModel.setText("Model");

        lblColor.setText("Color");

        lblOwnerAddress.setText("Owner Address ");

        lblYear.setText("Year");

        lblEngineNo.setText("Engine number");

        lblServiceRecords.setText("Service Records");

        lblSeatNumber.setText("Seat Numbers");

        lblLicensePlates.setText("License Plate");

        lblWarrantyYear.setText("Warranty Year");

        lblOwnerName.setText("Owner Name");

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "City", "Branch"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRecords);

        lblPhoto.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServiceRecords)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEngineNo)
                                        .addComponent(lblSeatNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblLicensePlates, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblBrand)
                                    .addComponent(lblModel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblYear)
                                        .addComponent(lblColor))
                                    .addComponent(lblWarrantyYear))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear)
                                    .addComponent(txtEngineNo)
                                    .addComponent(txtSeatNumbers)
                                    .addComponent(txtLicensePlates)
                                    .addComponent(txtModel)
                                    .addComponent(txtColor)
                                    .addComponent(txtWarrantyYear)
                                    .addComponent(txtBrand))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhotos)
                                .addGap(160, 160, 160)
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelephoneNumber)
                                    .addComponent(lblOwnerName)
                                    .addComponent(lblOwnerDriverLicense)
                                    .addComponent(lblOwnerEmailAddresses)
                                    .addComponent(lblOwnerSSN)
                                    .addComponent(lblOwnerAddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOwnerEmailAddresses)
                                    .addComponent(txtOwnerName)
                                    .addComponent(txtOwnerNumber)
                                    .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtOwnerSSN)
                                    .addComponent(txtOwnerAddress)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(lblCar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrand))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerName)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelephoneNumber)
                            .addComponent(txtOwnerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerEmailAddresses)
                    .addComponent(txtOwnerEmailAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerDriverLicense)
                    .addComponent(txtOwnerDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerSSN)
                    .addComponent(txtOwnerSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEngineNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSeatNumber)
                        .addComponent(txtSeatNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOwnerAddress)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicensePlates)
                    .addComponent(txtLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhotos)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWarrantyYear)
                        .addComponent(txtWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(lblServiceRecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblLicensePlates;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerAddress;
    private javax.swing.JLabel lblOwnerDriverLicense;
    private javax.swing.JLabel lblOwnerEmailAddresses;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerSSN;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotos;
    private javax.swing.JLabel lblSeatNumber;
    private javax.swing.JLabel lblServiceRecords;
    private javax.swing.JLabel lblTelephoneNumber;
    private javax.swing.JLabel lblWarrantyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTable tblRecords;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicensePlates;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerAddress;
    private javax.swing.JTextField txtOwnerDriverLicense;
    private javax.swing.JTextField txtOwnerEmailAddresses;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtOwnerNumber;
    private javax.swing.JTextField txtOwnerSSN;
    private javax.swing.JTextField txtSeatNumbers;
    private javax.swing.JTextField txtWarrantyYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void displayCar() {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    txtBrand.setText(car.getBrand());
    txtColor.setText(car.getColor());
    txtModel.setText(car.getModel());
    txtYear.setText(Integer.toString(car.getYear()));
    txtOwnerName.setText(car.getOwner_name());
    txtOwnerEmailAddresses.setText(car.getOwner_email_addresses());
    txtOwnerNumber.setText(car.getOwner_telephone_numbers());
    txtEngineNo.setText(car.getEngine_no());
    txtSeatNumbers.setText(Integer.toString(car.getSeatnumbers()));
    txtLicensePlates.setText(car.getLicenseplates());
    txtWarrantyYear.setText(Integer.toString(car.getWarranty_year()));
    txtOwnerDriverLicense.setText(car.getOwner_driverlicense());
     txtOwnerSSN.setText(Integer.toString(car.getOwner_SSN()));
     txtOwnerAddress.setText(car.getOwner_address());
     
     
        lblPhoto.setIcon(new ImageIcon(car.getPhoto()));
    
    }

    private void populateRecord() {
        
        DefaultTableModel model=  (DefaultTableModel) tblRecords.getModel();
        model.setRowCount(0);
        for(ServiceRecords rec:history.getHistory()){
            Object[] row = new Object[3];
            row[0]=rec.getDate();
            row[1]=rec.getMileage();
            row[2]=rec.getGas_capacity();
            if(!(rec.getDate()==null || rec.getMileage()==null || rec.getGas_capacity()==null)){
                   model.addRow(row);
            }
         
            
        }
        
      
    }
}
